### ISSUE TITLE
Shortcut to file

### ISSUE THREAD

**Issue by yoavrozner** [meateam/file-service#234]
Add CRUD for file shortcut. The shortcut can be in the "My Drive" and also in a folder in "Shared with me".
The idea behind the shortcut is that a user can edit the file from different locations and folders. That also includes folders in "Shared with me" page. This feature lets multiple users to edit a file's content which is the same file as the file of owner.

**Comment by yoavrozner** [comment]
file-service functions:

- [x] ShortcutFile class
- [x] Shortcut schema
- [x] Shortcut model
- [x] createShortcut in the repository
- [x] createShortcut in the service
- [x] createShortcut in the grpc
- [x] add the functionality to the server
- [x] add CreateShortcut rpc function to file.proto
- [x] update the get file + get files with population for shortcuts
- [x] add `isShortcut` property to the return type (in the proto and in the interface)
- [x] create a type converter function from IShortcut to IFIle
- [x] check type of get responses and handle accordingly (using the convert func)
- [x] use mongoose write operation findByIdAndUpdate() instead of updateOne()
- [x] work differently between models in updateById()
- [x] marker interface design pattern
- [x] delete all the console logs changes that i've made before committing: spec.helpers, logger, 


api-gateway functions:

- [x] update with the latest proto in the file-service
- [x] add function that validates and calls the file-service for the shortcut creation
- [x] add route for shortcut creation in file.go
- [x] CreateShortcut method todo in file.go

drive-ui functions:

- [x] add on right click the option to create a shortcut
- [x] add the shortcut popup that will decide where to put the shortcut
- [x] create a "יצירת קיצור דרך" button component
- [x] make a shortcut svg icon and use it in createShortcutButton

**Comment by yarinBenisty** [comment]
- [ ] לכתוב פונקציה שממירה ishortcut  ל - Ifile
- [ ] להכיל את זה על כל פעולות ה-גט ברפוסיטורי(אם זה שורטקט להכיל את הפונקציה עליו ואם לא אז להחזיר כרגיל)

**Comment by yarinBenisty** [comment]
Pretty much done with it :dagger:
